export const devKeywords = [
  "saas tips",
  "saas tools",
  "saas startups",
  "saas companies",
  "saas products",
  "saas services",
  "saas solutions",
  "dev tips",
  "dev tools",
  "dev startups",
  "dev companies",
  "dev products",
  "dev services",
  "dev solutions",
  "react tips",
  "nextjs tips",
  "tailwind tips",
  "typescript tips",
  "javascript tips",
];
